<a href="https://colab.research.google.com/github/khanabdulah871-png/Python-practice/blob/main/Diabaties_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Diabetes (1).csv')
print(df)

     pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0              6      148         72       35        0  33.6  0.627   50   
1              1       85         66       29        0  26.6  0.351   31   
2              8      183         64        0        0  23.3  0.672   32   
3              1       89         66       23       94  28.1  0.167   21   
4              0      137         40       35      168  43.1  2.288   33   
..           ...      ...        ...      ...      ...   ...    ...  ...   
763           10      101         76       48      180  32.9  0.171   63   
764            2      122         70       27        0  36.8  0.340   27   
765            5      121         72       23      112  26.2  0.245   30   
766            1      126         60        0        0  30.1  0.349   47   
767            1       93         70       31        0  30.4  0.315   23   

     diabetes  
0           1  
1           0  
2           1  
3           0  
4      

In [ ]:
df.head(21)

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0             6      148         72       35        0  33.6  0.627   50   
1             1       85         66       29        0  26.6  0.351   31   
2             8      183         64        0        0  23.3  0.672   32   
3             1       89         66       23       94  28.1  0.167   21   
4             0      137         40       35      168  43.1  2.288   33   
5             5      116         74        0        0  25.6  0.201   30   
6             3       78         50       32       88  31.0  0.248   26   
7            10      115          0        0        0  35.3  0.134   29   
8             2      197         70       45      543  30.5  0.158   53   
9             8      125         96        0        0   0.0  0.232   54   
10            4      110         92        0        0  37.6  0.191   30   
11           10      168         74        0        0  38.0  0.537   34   
12           10      139         80        0        0  27.1  1.441   57   
13            1      189         60       23      846  30.1  0.398   59   
14            5      166         72       19      175  25.8  0.587   51   
15            7      100          0        0        0  30.0  0.484   32   
16            0      118         84       47      230  45.8  0.551   31   
17            7      107         74        0        0  29.6  0.254   31   
18            1      103         30       38       83  43.3  0.183   33   
19            1      115         70       30       96  34.6  0.529   32   
20            3      126         88       41      235  39.3  0.704   27   

    diabetes  
0          1  
1          0  
2          1  
3          0  
4          1  
5          0  
6          1  
7          0  
8          1  
9          1  
10         0  
11         1  
12         0  
13         1  
14         1  
15         1  
16         1  
17         1  
18         0  
19         1  
20         0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.describe()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [ ]:
df.isnull().sum()

pregnancies    0
glucose        0
diastolic      0
triceps        0
insulin        0
bmi            0
dpf            0
age            0
diabetes       0
dtype: int64

In [ ]:
df.shape

(768, 9)

In [ ]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [ ]:
df.value_counts('diabetes')

diabetes
0    500
1    268
Name: count, dtype: int64

In [ ]:
df.groupby('diabetes').mean()

pregnancies     glucose  diastolic    triceps     insulin  \
diabetes                                                              
0            3.298000  109.980000  68.184000  19.664000   68.792000   
1            4.865672  141.257463  70.824627  22.164179  100.335821   

                bmi       dpf        age  
diabetes                                  
0         30.304200  0.429734  31.190000  
1         35.142537  0.550500  37.067164

In [ ]:
y = df['diabetes']

In [ ]:
y.shape

(768,)

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: diabetes, Length: 768, dtype: int64

In [ ]:
x = df.drop('diabetes', axis=1)

In [ ]:
x.shape

(768, 8)

In [ ]:
x

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0              6      148         72       35        0  33.6  0.627   50
1              1       85         66       29        0  26.6  0.351   31
2              8      183         64        0        0  23.3  0.672   32
3              1       89         66       23       94  28.1  0.167   21
4              0      137         40       35      168  43.1  2.288   33
..           ...      ...        ...      ...      ...   ...    ...  ...
763           10      101         76       48      180  32.9  0.171   63
764            2      122         70       27        0  36.8  0.340   27
765            5      121         72       23      112  26.2  0.245   30
766            1      126         60        0        0  30.1  0.349   47
767            1       93         70       31        0  30.4  0.315   23

[768 rows x 8 columns]

In [ ]:
m = MinMaxScaler()

In [ ]:
x = m.fit_transform(x)

In [ ]:
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state=2529)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((537, 8), (231, 8), (537,), (231,))

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
y_pred.shape

(231,)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
lr.predict_proba(X_test)

array([[0.71103946, 0.28896054],
       [0.80270043, 0.19729957],
       [0.50024494, 0.49975506],
       [0.87453281, 0.12546719],
       [0.84327888, 0.15672112],
       [0.72976287, 0.27023713],
       [0.32533912, 0.67466088],
       [0.82925861, 0.17074139],
       [0.57780995, 0.42219005],
       [0.58037119, 0.41962881],
       [0.90526788, 0.09473212],
       [0.42445722, 0.57554278],
       [0.81675638, 0.18324362],
       [0.86059521, 0.13940479],
       [0.55621701, 0.44378299],
       [0.83246253, 0.16753747],
       [0.40586938, 0.59413062],
       [0.8432027 , 0.1567973 ],
       [0.603806  , 0.396194  ],
       [0.51914277, 0.48085723],
       [0.65191019, 0.34808981],
       [0.89681578, 0.10318422],
       [0.88362429, 0.11637571],
       [0.50440599, 0.49559401],
       [0.74028059, 0.25971941],
       [0.38055467, 0.61944533],
       [0.86757912, 0.13242088],
       [0.63021062, 0.36978938],
       [0.54630712, 0.45369288],
       [0.16759088, 0.83240912],
       [0.

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[136  14]
 [ 37  44]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.91      0.84       150
           1       0.76      0.54      0.63        81

    accuracy                           0.78       231
   macro avg       0.77      0.72      0.74       231
weighted avg       0.78      0.78      0.77       231



In [ ]:
x_new = df.sample(1)

In [ ]:
x_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
434            1       90         68        8        0  24.5  1.138   36   

     diabetes  
434         0

In [ ]:
x_new.shape

(1, 9)

In [ ]:
x_new = x_new.drop('diabetes', axis=1)
x_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
434            1       90         68        8        0  24.5  1.138   36

In [ ]:
x_new.shape

(1, 8)

In [ ]:
x_new = m.fit_transform(x_new)

In [ ]:
y_pred_new = lr.predict(x_new)
y_pred_new

array([0])

In [ ]:
lr.predict_proba(x_new)

array([[0.99511171, 0.00488829]])

Predicted and Actual class in zero that means Non_diabetic